spring:
  config:
    activate:
      on-profile: dev # Se define que este .yaml es para el profile dev

server: # NOTA: server va al mismo nivel que spring
  port: 8081

#Añadido debug para ver los logs en desarrollo
logging:
  level:
    com.programandoenjava.bootcamp_1_2026: DEBUG