spring:
  # Configuración DB H2 para desarrollo
  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  # Configuración JPA específica de dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true

  # Configuración JWT para OAuth2 Resource Server
  # secret-key la usará Spring automáticamente para validar los tokens
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}
          expiration: 86400000
          refresh-token-expiration: 604800000

# Puerto
server:
  port: 8081

# Logging en modo DEBUG
logging:
  level:
    com.programandoenjava.bootcamp_1_2026: DEBUG