spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Configuración de Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Configuración JPA específica de prod
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: ecommerce
        generate_statistics: false
        format_sql: false

# Puerto
server:
  port: 8081

# Configuración JWT
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION} # 1 día en ms
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION} # 7 días en ms

# Aquí defino las propiedades de la aplicación, app es una convención
# podría ser feature o cualquier cosa
app:
  payment-provider: paypal # Propiedad que indica que servicio se va a usar para los pagos en "prod"
  stripe-key: ${STRIPE_API_KEY}
  paypal-key: ${PAYPAL_API_KEY}

# Logging en modo INFO
logging:
  level:
    com.programandoenjava.bootcamp_1_2026: INFO
