spring:
  application:
    name: bootcamp-1-2026
  profiles:
    active: dev # Si se ejecuta por comandos, se ignora por jerarquía

  # Configuración JPA común
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 20 # IMPORTANTE: Esto no funciona a nivel de lectura SOLO ESCRITURA
          batch_versioned_data: true # IMPORTANTE: Permite batching en entidades que usan @Version
        order_inserts: true # Agrupa todos los INSERT del mismo tipo de entidad juntos
        order_updates: true # Agrupa todos los UPDATE del mismo tipo de entidad juntos