spring:
  # Configuración DB H2 para desarrollo
  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  # Configuración JPA específica de dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true

# Configuración JWT
application:
  security:
    jwt:
      #Clave de 256 Bits generada en https://jwtsecrets.com/,
      #la dejo educativamente, pero debería ser una variable de entorno
      secret-key: 99da4c928ac546b3e267b11f1ec1c189d331b4a151d96a811c466696d545b194
      expiration: 86400000 # 1 día en ms
      refresh-token:
        expiration: 604800000 # 7 días en ms

# Puerto
server:
  port: 8081

# Logging en modo DEBUG
logging:
  level:
    com.programandoenjava.bootcamp_1_2026: DEBUG